services:
  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: gtd_app
  web:
    image: nginx:1.27-alpine
    ports:
      - "8080:80"
    volumes:
      # Serve your static site from ./public
      - ./public:/usr/share/nginx/html:ro
volumes:
  mongo_data:
