# Use the official Python runtime as a base image
FROM python:3.11

# Set the working directory to /app
WORKDIR /app

# Add the current directory contents into the container at /app
COPY ./src /app

# Install any needed packages specified in requirements.txt
RUN pip install -r requirements.txt

# Make port 8000 available to the world outside this container
EXPOSE 8000

# Define environment variable
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Run the command to start the application
# CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
